# Github Library
github:
  name: KMPPlatformContext
  release: 2025
  namespace: com.michaelflisar.kmp.platformcontext
  license:
    name: Apache License 2.0
    path: blob/main/LICENSE

# Maven
maven:
  group-id: io.github.mflisar.kmpplatformcontext
  primary-artifact-id: core # used to detect latest release version of the library (dynamically on the published homepage)

# Modules - list of modules [artifact-id, description, path]
modules:
  - artifact-id: core
    description: This is the core module that holds the android app context
    path: library/core
  - artifact-id: initializer
    description: Uses androidx.startup to automatically initialize the android context on app start
    path: library/initializer

# XCFrameworks [name, path, targets (ios, macos)]
xcframeworks: []